/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RvnNAC46L39
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { getProductById } from "@/actions/product"
import { getUserData } from "@/actions/auth"
import RelatedProducts from "../functional/RelatedProducts"
import { ProductViewClient } from "./productview-client"
import { productData } from "@/types/product"
import ImagePreviwer from "../functional/ImagePreviwer"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

interface ProductviewProps {
  productId: string
  category: string
}

export async function Productview({productId, category}: ProductviewProps) {
  const product: productData = await getProductById({id: productId})
  const user = await getUserData()

  if(!product){
      return null
  }

  // Use the category from the product data if not provided in URL
  const productCategory = category || (product as any).category || 'electronics'

  return (
    <div className="md:grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-[1500px] px-4 mx-auto py-6">

      <ImagePreviwer images={product.images}/>

      <div className="grid gap-4 md:gap-10 items-start md:py-0 py-6">
        <div className="grid gap-4">
          <h1 className="font-bold text-3xl lg:text-4xl">{product.name}</h1>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-0.5">
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
            </div>
            <div className="text-4xl font-bold">₹{product.price}</div>
          </div>
          <div className="text-sm leading-loose text-muted-foreground">
            <p>
              {product.description}
            </p>
          </div>
        </div>
        <ProductViewClient product={product} productId={productId} user={user} />
      </div>
      
      <div className="col-span-2 grid gap-8">
        <Card>
          <CardHeader>
            <CardTitle>Product Specifications</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 text-sm leading-loose">
              <div>
                <h3 className="font-semibold">Material</h3>
                <p>{product.product_specification?.material || "Not specified"}</p>
              </div>
              <div>
                <h3 className="font-semibold">Care Instructions</h3>
                <p>{product.product_specification?.careInstruction || "Not specified"}</p>
              </div>
              <div>
                <h3 className="font-semibold">Dimensions</h3>
                <p>{product.product_specification?.dimensions || "Not specified"}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>Customer Reviews</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-6">
              <div className="flex gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div className="grid gap-4">
                  <div className="flex gap-4 items-start">
                    <div className="grid gap-0.5 text-sm">
                      <h3 className="font-semibold">Sarah Johnson</h3>
                      <time className="text-sm text-muted-foreground">2 days ago</time>
                    </div>
                    <div className="flex items-center gap-0.5 ml-auto">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    </div>
                  </div>
                  <div className="text-sm leading-loose text-muted-foreground">
                    <p>
                      I've been experimenting with my {product.name} for a few weeks now, and it's been a versatile
                      addition to my wardrobe. The fabric is comfortable and the design is unique.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      
      <div className="col-span-2">
        <RelatedProducts category={productCategory} _id={productId} />
      </div>
    </div>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
      </svg>
    )
  }
